{{- if .Values.server.route -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "argo-cd.server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-{{ .Values.server.name }}
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.server.name }}
{{- with .Values.server.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  host: {{ .Values.server.route.hostname | quote }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ template "argo-cd.server.fullname" . }}
    weight: 100
status:
  ingress:
    - conditions:
      - lastTransitionTime: "2019-12-06T03:24:58Z"
        status: "True"
        type: Admitted
      host: <host>
      routerCanonicalHostname: <host>
      routerName: default
      wildcardPolicy: None
{{ end }}
